dist: trusty
language: php

# Only test the master branch and SemVer tags.
branches:
  only:
    - master
    - '/^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/'

matrix:
  include:
    -
      php: 7.1
      env: 'HIGHEST_LOWEST="update"'
    -
      php: 7.0.11
    -
      php: 5.5
      env: 'HIGHEST_LOWEST="update --prefer-lowest"'

# Builds are faster if we do not need to sudo
sudo: false

# Store the composer cache for faster builds
cache:
  directories:
    - $HOME/.composer/cache

# Do highest/lowest testing by installing dependencies per the 'dependencies' setting
before_script:
  - 'composer -n ${HIGHEST_LOWEST-install} --prefer-dist'

script:
  - 'composer -n test'

# Process coveralls
after_success:
  - 'travis_retry php vendor/bin/coveralls -v'
